[package]
name = "mysql_learning"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mysql_learning"
path = "src/main.rs"

[dependencies]
mysql = "25.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
#urlencoding = { version = "1.1", features = ["feature-name"] }